export const OPPORTUNITY_TABS = [
  { id: "all", label: "All Opportunities", count: "12,840", icon: "grid" },
  { id: "govt", label: "Government Exams", count: "8,340", icon: "building", active: true },
  { id: "internships", label: "Internships", count: "420", icon: "academic" },
  { id: "wfh", label: "Work From Home", count: "380", icon: "home" },
  { id: "state_govt", label: "State Govt. Jobs", count: "1,180", icon: "key" },
  { id: "teaching", label: "Teaching Jobs", count: "640", icon: "users" },
  { id: "defence", label: "Defence Jobs", count: "310", icon: "shield" },
];

export const GOVT_EXAMS = [
  {
    id: 1,
    title: "UPSC Civil Services (IAS)",
    organization: "Union Public Service Commission",
    emblem: "https://upload.wikimedia.org/wikipedia/commons/5/55/Emblem_of_India.svg",
    scope: "National",
    status: "Apply Soon",
    statusType: "soon", // green
    vacancies: "1,056 Vacancies",
    date1Label: "Notification",
    date1Value: "Feb 2025",
    date2Label: "Exam",
    date2Value: "May 2025",
    tags: ["IAS", "IPS", "IFS"],
    extraTagsCount: 2,
    btnText: "View Details \u2192",
    btnVariant: "primary",
  },
  {
    id: 2,
    title: "RRB NTPC",
    organization: "Indian Railways",
    emblem: "https://upload.wikimedia.org/wikipedia/en/4/45/Indian_Railways_logo.svg",
    scope: "National",
    status: "Ongoing",
    statusType: "ongoing", // red/pink
    vacancies: "11,558 Vacancies",
    date1Label: "Apply till",
    date1Value: "20 Sep 2025",
    date2Label: "Exam",
    date2Value: "Nov 2025",
    tags: ["Railway", "NTPC", "Graduate"],
    extraTagsCount: 0,
    btnText: "Apply Now \u2192",
    btnVariant: "outline",
  },
  {
    id: 3,
    title: "SSC CGL",
    organization: "Staff Selection Commission",
    emblem: "/Staff_Selection_Commission_Logo.jpg",
    scope: "National",
    status: "Upcoming",
    statusType: "upcoming", // purple
    vacancies: "7,500+ Vacancies",
    date1Label: "Notification",
    date1Value: "Oct 2025",
    date2Label: "Exam",
    date2Value: "Jan 2026",
    tags: ["CGL", "CHSL", "MTS"],
    extraTagsCount: 1,
    btnText: "View Details \u2192",
    btnVariant: "gradient",
  },
  {
    id: 4,
    title: "West Bengal SSC",
    organization: "School Service Commission",
    emblem: "https://upload.wikimedia.org/wikipedia/commons/5/55/Emblem_of_India.svg",
    scope: "State",
    status: "Apply Now",
    statusType: "apply", // green
    vacancies: "24,640 Vacancies",
    date1Label: "Apply till",
    date1Value: "30 Sep 2025",
    date2Label: "Exam",
    date2Value: "Dec 2025",
    tags: ["Teaching", "Class 9-12", "State Govt."],
    extraTagsCount: 0,
    btnText: "Apply Now \u2192",
    btnVariant: "outline",
  },
];

export const PRIVATE_JOBS = [
  {
    id: 1,
    title: "Software Engineer",
    company: "Google",
    logo: "https://www.svgrepo.com/show/303108/google-icon-logo.svg",
    location: "Bangalore, India",
    type: "Full-time",
    salary: "₹20L – ₹35L",
    posted: "3 days ago",
  },
  {
    id: 2,
    title: "Product Manager",
    company: "Microsoft",
    logo: "https://www.svgrepo.com/show/303266/microsoft-logo.svg",
    location: "Hyderabad, India",
    type: "Full-time",
    salary: "₹25L – ₹45L",
    posted: "1 week ago",
  },
  {
    id: 3,
    title: "Data Analyst",
    company: "TCS",
    logo: "https://www.svgrepo.com/show/303273/tata-motors-logo.svg",
    location: "Pune, India",
    type: "Full-time",
    salary: "₹8L – ₹14L",
    posted: "5 days ago",
  },
  {
    id: 4,
    title: "UI/UX Designer",
    company: "IBM",
    logo: "https://www.svgrepo.com/show/303274/ibm-logo.svg",
    location: "Remote",
    type: "Full-time",
    salary: "₹12L – ₹22L",
    posted: "4 days ago",
  },
];
