export const CATEGORIES = [
  {
    id: 1,
    title: "Software Development",
    jobs: "2,450+ Jobs",
    icon: "laptop",
    iconBg: "#dbeafe",
    iconColor: "#2563eb",
    arrowBg: "#2563eb",
    arrowColor: "#ffffff",
    highlight: true,
  },
  {
    id: 2,
    title: "Design & Creative",
    jobs: "850+ Jobs",
    icon: "palette",
    iconBg: "#fce7f3",
    iconColor: "#ec4899",
    arrowBg: "#fdf2f8",
    arrowColor: "#ec4899",
    highlight: false,
  },
  {
    id: 3,
    title: "Data & Analytics",
    jobs: "1,120+ Jobs",
    icon: "chart",
    iconBg: "#dcfce7",
    iconColor: "#16a34a",
    arrowBg: "#f0fdf4",
    arrowColor: "#16a34a",
    highlight: false,
  },
  {
    id: 4,
    title: "Marketing & Sales",
    jobs: "740+ Jobs",
    icon: "megaphone",
    iconBg: "#ffedd5",
    iconColor: "#ea580c",
    arrowBg: "#fff7ed",
    arrowColor: "#ea580c",
    highlight: false,
  },
  {
    id: 5,
    title: "Business & Finance",
    jobs: "920+ Jobs",
    icon: "briefcase",
    iconBg: "#f3e8ff",
    iconColor: "#9333ea",
    arrowBg: "#faf5ff",
    arrowColor: "#9333ea",
    highlight: false,
  },
  {
    id: 6,
    title: "Human Resources",
    jobs: "430+ Jobs",
    icon: "users",
    iconBg: "#fef9c3",
    iconColor: "#ca8a04",
    arrowBg: "#fefce8",
    arrowColor: "#ca8a04",
    highlight: false,
  },
  {
    id: 7,
    title: "Product Management",
    jobs: "680+ Jobs",
    icon: "gear",
    iconBg: "#cffafe",
    iconColor: "#0891b2",
    arrowBg: "#ecfeff",
    arrowColor: "#0891b2",
    highlight: false,
  },
  {
    id: 8,
    title: "Healthcare",
    jobs: "510+ Jobs",
    icon: "heart",
    iconBg: "#ffe4e6",
    iconColor: "#e11d48",
    arrowBg: "#fff1f2",
    arrowColor: "#e11d48",
    highlight: false,
  },
  {
    id: 9,
    title: "Education",
    jobs: "320+ Jobs",
    icon: "academic",
    iconBg: "#d1fae5",
    iconColor: "#059669",
    arrowBg: "#ecfdf5",
    arrowColor: "#059669",
    highlight: false,
  },
  {
    id: 10,
    title: "Government",
    jobs: "280+ Jobs",
    icon: "building",
    iconBg: "#ede9fe",
    iconColor: "#7c3aed",
    arrowBg: "#f5f3ff",
    arrowColor: "#7c3aed",
    highlight: false,
  },
  {
    id: 11,
    title: "Hospitality & Travel",
    jobs: "390+ Jobs",
    icon: "plane",
    iconBg: "#ffedd5",
    iconColor: "#f97316",
    arrowBg: "#fff7ed",
    arrowColor: "#f97316",
    highlight: false,
  },
  {
    id: 12,
    title: "Others",
    jobs: "1,200+ Jobs",
    icon: "dots",
    iconBg: "#e0f2fe",
    iconColor: "#0284c7",
    arrowBg: "#f0f9ff",
    arrowColor: "#0284c7",
    highlight: false,
  },
];

export const CATEGORY_HIGHLIGHTS = [
  {
    id: 1,
    icon: "target",
    iconBg: "#eff6ff",
    iconColor: "#2563eb",
    title: "Wide Opportunities",
    subtitle: "Jobs across multiple industries",
  },
  {
    id: 2,
    icon: "star",
    iconBg: "#f5f3ff",
    iconColor: "#8b5cf6",
    title: "Trusted Companies",
    subtitle: "Work with top brands",
  },
  {
    id: 3,
    icon: "users",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    title: "Career Growth",
    subtitle: "Find roles that match your goals",
  },
  {
    id: 4,
    icon: "shield",
    iconBg: "#fff1f2",
    iconColor: "#f43f5e",
    title: "Verified Listings",
    subtitle: "100% genuine job posts",
  },
];
